import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Code Editor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button className="bg-blue-500 px-4 py-2 m-2 rounded-md shadow-md">
          Register
        </button>
      </main>
    </>
  );
}
