import Header from "@/components/header/Header";
import styled from "@emotion/styled";
import Head from "next/head";

const LayoutContainer = styled("div")({
  height: "100%",
  display: "flex",
  flexDirection: "column",
});

const Page = styled("div")({
  height: "100%",
});

function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutContainer>
        <Header />
        <Page>{children}</Page>
      </LayoutContainer>
    </>
  );
}

export default Layout;
